"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# https://docs.djangoproject.com/en/5.1/ref/settings/#std:setting-BASE_DIR

BASE_DIR = Path(__file__).resolve().parent.parent


# Debug Mode
# https://docs.djangoproject.com/en/5.1/ref/settings/#std:setting-DEBUG

DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)


# Django Secret Key
# https://docs.djangoproject.com/en/5.1/ref/settings/#secret-key

SECRET_KEY = config('DJANGO_SECRET_KEY', default="banana")



# Allowed Hosts
# https://docs.djangoproject.com/en/5.1/ref/settings/#allowed-hosts

ALLOWED_HOSTS = ['*']


# Application definition
# https://docs.djangoproject.com/en/5.1/ref/settings/#installed-apps

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.user',
    'apps.group',
    'apps.meeting',
]


# Redirects
# https://docs.djangoproject.com/en/5.1/ref/settings/#login-redirect-url

LOGIN_URL = '/user/authentication/'

LOGIN_REDIRECT_URL = '/user/'

LOGOUT_REDIRECT_URL = '/user/authentication/'


# Rest framework
# https://docs.djangoproject.com/en/5.1/ref/settings/#rest-framework

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}


# Middleware5
# https://docs.djangoproject.com/en/5.1/topics/http/middleware/

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# Root URL configuration
# https://docs.djangoproject.com/en/5.1/ref/settings/#root-urlconf

ROOT_URLCONF = 'config.urls'


# CSRF
# https://docs.djangoproject.com/en/5.1/ref/settings/#csrf-cookie-name

CSRF_COOKIE_NAME = 'csrftoken'

CSRF_COOKIE_SECURE = True

CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'


# Django Security
# https://docs.djangoproject.com/en/5.1/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

SECURE_SSL_REDIRECT = True

SESSION_COOKIE_SECURE = True


# Templates
# https://docs.djangoproject.com/en/5.1/ref/settings/#templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# WSGI
# https://docs.djangoproject.com/en/5.1/ref/settings/#wsgi-application

WSGI_APPLICATION = 'config.wsgi.application'


# ASGI
# https://docs.djangoproject.com/en/5.1/ref/settings/#asgi-application

ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': 'postgres',
        'PORT': config('POSTGRES_INTERNAL_PORT'),
        'CONN_MAX_AGE': 600,
    }
}


# Password hashers
# https://docs.djangoproject.com/en/5.1/ref/settings/#password-hashers

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Authentication backends
# https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#specifying-authentication-backends


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django Redis
# https://django-redis.readthedocs.io/en/latest/

CACHE = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://{}:{}@redis:redis/{}'.format(
            config('REDIS_PASSWORD'),
            config('REDIS_INTERNAL_PORT'),
            config('REDIS_DB'),
        ),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
    }
}


# Websocket backend settings

WEBSOCKET_URL = 'http://websocket:{}/'.format(config('WEBSOCKET_INTERNAL_PORT'))


# Annotator backend settings

ANNOTATOR_URL = 'http://annotator:{}/'.format(config('ANNOTATOR_INTERNAL_PORT'))
